openapi: 3.0.0
info:
  title: Kudos API
  description: API for users to give and receive kudos in their organization.
  version: 1.0.0

servers:
  - url: http://127.0.0.1:8000/api
    description: Local Development Server

paths:
  /login/:
    post:
      summary: User Login
      description: Authenticates a user and returns an auth token.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user_id:
                    type: integer
                  username:
                    type: string
        400:
          description: Invalid credentials

  /logout/:
    post:
      summary: User Logout
      description: Logs out the user by deleting the authentication token.
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successfully logged out

  /users/:
    get:
      summary: Get List of Users
      description: Returns a list of all users in the system.
      security:
        - bearerAuth: []
      responses:
        200:
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    username:
                      type: string
                    email:
                      type: string
                    organization:
                      type: string
                    kudos_remaining:
                      type: integer

  /kudos/give/:
    post:
      summary: Give Kudos to a User
      description: Allows a user to give kudos to another user within their organization.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipient_id:
                  type: integer
                message:
                  type: string
      responses:
        201:
          description: Kudos successfully given
        400:
          description: Validation error (e.g., not enough kudos left)

  /kudos/received/:
    get:
      summary: Get Kudos Received
      description: Returns a list of kudos the logged-in user has received.
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of kudos received
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    sender:
                      type: string
                    message:
                      type: string
                    timestamp:
                      type: string
                      format: date-time

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer