# docker-compose.yml
version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"  # Expose backend on port 8000
    volumes:
      - ./backend/app:/app  # Mount backend code (optional for production)
    environment:
      - DEBUG=0  # Disable debug mode for production
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1  # Adjust as needed

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"